model: "microsoft/mpnet-base"
output_dir: "../model"
num_train_epochs: 2
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
learning_rate: 0.00002
warmup_ratio: 0.1
fp16: false
bf16: true
eval_strategy: "epoch"
save_strategy: "epoch"
save_total_limit: 2
